# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-05 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOfficeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.MedicalOfficer')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.BranchOffice')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_call_code', models.CharField(max_length=15)),
                ('call_status', models.CharField(choices=[('onprogress', 'On Progress'), ('success', 'Success'), ('done', 'Done'), ('fail', 'Fail')], max_length=10)),
                ('evidence_lat', models.FloatField()),
                ('evidence_lon', models.FloatField()),
                ('evidence_place', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_lat', models.FloatField()),
                ('last_lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency_call_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.EmergencyCall')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.MedicalOfficer')),
            ],
        ),
    ]
