# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-13 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_emergencyteam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycall',
            name='evidence_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
