# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-05 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('salutation', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('sir', 'Sir'), ('lady', 'Lady')], max_length=10)),
                ('code', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=25)),
                ('police_certificate_code', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalOfficer',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_profile.BaseProfile')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('psychologist', 'Psychologist'), ('physiotherapist', 'Physio Therapist')], max_length=10)),
                ('skillset', models.TextField()),
            ],
            bases=('user_profile.baseprofile',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_profile.BaseProfile')),
                ('medical_symptomps', models.TextField()),
            ],
            bases=('user_profile.baseprofile',),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
