# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='police_certificate_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
