# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20181212_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalofficer',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('psychologist', 'Psychologist'), ('physiotherapist', 'Physio Therapist')], max_length=30),
        ),
    ]
