# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-05 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocationTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('device_id', models.CharField(blank=True, max_length=25)),
                ('device_manufacturer', models.CharField(blank=True, max_length=50)),
                ('device_model', models.CharField(blank=True, max_length=25)),
                ('device_os', models.CharField(blank=True, max_length=25)),
                ('device_type', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('device_battery_level', models.IntegerField(blank=True)),
                ('device_uptime', models.TimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
