# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocationtracker',
            name='device_manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geolocationtracker',
            name='device_model',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='geolocationtracker',
            name='device_os',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='geolocationtracker',
            name='device_uptime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
